---
title: "Multivariante"
author: "Curso de Estadística Descriptiva"
date: "24/12/2018"
output: html_document
---

# Datos multidimensionales

## Ejemplo con tres dimensiones

```{r}
ans = sample(c("Si", "No"), size = 100, replace = TRUE)
sex = sample(c("H", "M"), size = 100, replace = TRUE)
place = sample(c("San Francisco", "Barcelona", "Valencia", "Cobija", "Asturias"), size = 100, replace = TRUE)
table(sex, ans, place)
ftable(sex, ans, place)
ftable(sex, ans, place, col.vars = c("sex", "ans"))
```

### Filtrar las tablas

```{r}
table(sex, ans, place)["M", "Si", "San Francisco"]
table(sex, ans, place)[ , "Si", "Valencia"]
table(sex, ans, place)[ , "No", ]
table(sex, ans, place)["M", , "Cobija"]
```

### Frecuencias relativas 
```{r}
prop.table(table(sex, ans, place))#Frec. Rel. Globales
prop.table(table(sex, ans, place), margin = 3) # Frec. Rel. Marginal por Lugar
prop.table(table(sex, ans, place), margin = c(1, 3)) # Frec. Rel. Marg. por Sexo y País

ftable(prop.table(table(sex, ans, place)))
```

