---
title: "Prueba"
author: "María Santos"
date: "1 de junio de 2017"
output: html_document
---
#Carga de datos

```{r}
etiq_largas=c("Classes","Alcohol","Malic Acid","Ash","Alcalinity of ash","Magnesium","Total phenols","Flavanoids","NonFlavanoid phenols","Proanthocyanins","Color intensity","Hue","OD280/OD315 of diluted wines","Proline")
vinos=read.table("http://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data",sep=",",colClasses=c("factor",rep("numeric",13)),col.names=etiq_largas )
str(vinos)
```

```{r}
estadisticos=function(x){c(mean(x),sd(x),median(x))}
aggregate(Alcohol~Classes,data=vinos,FUN="estadisticos")
boxplot(vinos$Alcohol~vinos$Classes,main="Cantidad de alcohol por clases")
cov(vinos[,-1])
cor(vinos[,-1])
pairs(vinos[,-1])
cor(vinos$Total.phenols,vinos$Flavanoids)
n=dim(vinos)[1]
medias=apply(vinos[,-1],2,FUN="mean")
desv.tip=apply(vinos[,-1],2,FUN=function(x) sd(x)*sqrt((length(x)-1)/length(x)))
desv.tip
vinos.tipif=scale(vinos[,-1],center=medias,scale=desv.tip)
MD=dist(vinos.tipif,method="euclidean")
```

```{r}
sol=hclust(MD,method="average")
plot(sol,labels=vinos$Classes,main="Clustering")
cutter=cutree(sol,h=4)
cutter
table(cutter,vinos$Classes)
solkm=kmeans(vinos[,-1],6)
table(solkm$cluster,vinos$Classes)
```


